/*
 * Swagger Petstore
 *
 * This is a sample Petstore server.  You can find  out more about Swagger at  [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	"github.com/rs/cors"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "go-honghub/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	handler := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "PUT", "PATCH", "POST", "DELETE"},
		ExposedHeaders:   []string{"Content-Length"},
		AllowedHeaders:   []string{"*"},
		AllowCredentials: true,
		MaxAge:           12 * 60 * 60,
	}).Handler(router)
	log.Fatal(http.ListenAndServe(":8080", handler))
}
